/**
 * The "Custom" theme: a user-defined palette applied at runtime by writing the
 * `--rw-*` custom properties inline on <html> (which is :root, so they win over
 * the stylesheet). Persisted per browser. No build step — pick colors, see them
 * live — and exportable as a committable themes/<id>.css for permanent use.
 */
import { TOKENS, defaultPalette, type Palette } from './tokens';

const STORAGE_KEY = 'rw-custom-palette';
export const CUSTOM_THEME_ID = 'custom';

export function loadCustomPalette(): Palette {
  const base = defaultPalette();
  try {
    const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? '{}') as Palette;
    return { ...base, ...saved };
  } catch {
    return base;
  }
}

export function saveCustomPalette(palette: Palette): void {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(palette));
}

/** Read the currently-rendered value of each token (to seed the editor). */
export function readActivePalette(): Palette {
  const p = defaultPalette();
  if (typeof window === 'undefined') return p;
  const cs = getComputedStyle(document.documentElement);
  for (const t of TOKENS) {
    const v = cs.getPropertyValue(t.var).trim();
    if (v) p[t.key] = v;
  }
  return p;
}

export function applyCustomPalette(palette: Palette): void {
  if (typeof window === 'undefined') return;
  const style = document.documentElement.style;
  for (const t of TOKENS) style.setProperty(t.var, palette[t.key] ?? t.default);
}

export function clearCustomPalette(): void {
  if (typeof window === 'undefined') return;
  const style = document.documentElement.style;
  for (const t of TOKENS) style.removeProperty(t.var);
}

/** Export the palette as a committable theme stylesheet. */
export function exportThemeCss(id: string, palette: Palette): string {
  const safeId = id.trim().toLowerCase().replace(/[^a-z0-9-]+/g, '-') || 'custom';
  const lines = TOKENS.map((t) => `  ${t.var}: ${palette[t.key] ?? t.default};`);
  return [
    `/* Theme: ${safeId} — generated by the RepoWrangler Theme Studio */`,
    `[data-theme='${safeId}'] {`,
    ...lines,
    `  color-scheme: light;`,
    `}`,
    '',
  ].join('\n');
}
